extends TextureRect

func _ready():
	while true:
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00006.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00007.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00008.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00009.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00010.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00011.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00012.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00013.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00014.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00015.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00016.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00017.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00018.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00019.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00020.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00021.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00022.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00023.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00024.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00025.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00026.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00027.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00028.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00029.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00030.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00031.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00032.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00033.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00034.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00035.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00036.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00037.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00038.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00039.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00040.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00041.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00042.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00043.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00044.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00045.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00046.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00047.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00048.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00049.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00050.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00051.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00052.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00053.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00054.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00055.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00056.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00057.png")
		yield(get_tree().create_timer(0.015), "timeout")
		texture = load("res://LoadingAnim/loading00058.png")
